[project]
name = "moe-null"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.10.0",
    "tiktoken>=0.9.0",
    "matplotlib>=3.10.0",
    "gradio>=6.5.1",
    "onnxscript>=0.6.2",
]
